// Generated by bin/api-error-contract --generate. Do not edit.
package com.getmaincourse.app.data.network

enum class ApiErrorCode(val wire: String) {
    ACCOUNT_LINK_REQUIRED("account_link_required"),
    ALREADY_COOKBOOK_MEMBER("already_cookbook_member"),
    APP_UPDATE_REQUIRED("app_update_required"),
    APPLE_ACCOUNT_CREATION_CONFIRMATION_REQUIRED("apple_account_creation_confirmation_required"),
    CONTENT_TOO_LARGE("content_too_large"),
    COOKBOOK_UNAVAILABLE("cookbook_unavailable"),
    DELETE_FAILED("delete_failed"),
    FORBIDDEN("forbidden"),
    IMAGE_REQUIRED("image_required"),
    IMAGE_TOO_LARGE("image_too_large"),
    IMPORT_LIMIT_REACHED("import_limit_reached"),
    INVALID_CREDENTIALS("invalid_credentials"),
    INVALID_IMAGE("invalid_image"),
    INVALID_IMPORT_URL("invalid_import_url"),
    INVALID_RECIPE_SAVE("invalid_recipe_save"),
    INVALID_REQUEST("invalid_request"),
    INVALID_SHOPPING_ITEMS("invalid_shopping_items"),
    INVITATION_UNAVAILABLE("invitation_unavailable"),
    MEAL_PLAN_FINALIZED("meal_plan_finalized"),
    MEAL_PLAN_SELECTION_CONFLICT("meal_plan_selection_conflict"),
    NAME_REQUIRED("name_required"),
    NOT_FOUND("not_found"),
    OAUTH_FAILED("oauth_failed"),
    OAUTH_UNAVAILABLE("oauth_unavailable"),
    OWNER_CANNOT_LEAVE("owner_cannot_leave"),
    OWNER_REQUIRED("owner_required"),
    PERSONAL_COOKBOOK_INVITATION("personal_cookbook_invitation"),
    PERSONAL_COOKBOOK_REQUIRED("personal_cookbook_required"),
    RATE_LIMITED("rate_limited"),
    RECIPE_SAVE_CONFLICT("recipe_save_conflict"),
    RECIPE_SAVE_GONE("recipe_save_gone"),
    SHARED_COOKBOOK_EXISTS("shared_cookbook_exists"),
    TEXT_REQUIRED("text_required"),
    TEXT_TOO_LONG("text_too_long"),
    UNAUTHORIZED("unauthorized"),
    UPDATE_FAILED("update_failed"),
    URL_REQUIRED("url_required"),
    VALIDATION_FAILED("validation_failed");

    companion object {
        fun fromWire(value: String?): ApiErrorCode? = entries.find { it.wire == value }
    }
}

enum class ImportErrorCode(val wire: String) {
    IMPORT_FAILED("import_failed"),
    NO_RECIPE_IN_PHOTO("no_recipe_in_photo");

    companion object {
        fun fromWire(value: String?): ImportErrorCode? = entries.find { it.wire == value }
    }
}

enum class ValidationFieldCode(val wire: String) {
    BASE("base"),
    COOK_TIME("cook_time"),
    COVER_IMAGE("cover_image"),
    EMAIL_ADDRESS("email_address"),
    IMPORT_IMAGE("import_image"),
    NAME("name"),
    PASSWORD("password"),
    PASSWORD_CHALLENGE("password_challenge"),
    PASSWORD_CONFIRMATION("password_confirmation"),
    PREP_TIME("prep_time"),
    SERVINGS("servings"),
    SOURCE_URL("source_url");

    companion object {
        fun fromWire(value: String?): ValidationFieldCode? = entries.find { it.wire == value }
    }
}

enum class ValidationRuleCode(val wire: String) {
    BLANK("blank"),
    CONFIRMATION("confirmation"),
    INVALID("invalid"),
    PASSWORD_TOO_LONG("password_too_long"),
    TAKEN("taken"),
    TOO_LONG("too_long"),
    TOO_SHORT("too_short");

    companion object {
        fun fromWire(value: String?): ValidationRuleCode? = entries.find { it.wire == value }
    }
}
