enum ApiErrorCode: String, CaseIterable {
    // Generated by bin/api-error-contract --generate. Do not edit.
    case account_link_required
    case already_cookbook_member
    case app_update_required
    case apple_account_creation_confirmation_required
    case content_too_large
    case cookbook_unavailable
    case delete_failed
    case forbidden
    case image_required
    case image_too_large
    case import_limit_reached
    case invalid_credentials
    case invalid_image
    case invalid_import_url
    case invalid_recipe_save
    case invalid_request
    case invalid_shopping_items
    case invitation_unavailable
    case meal_plan_finalized
    case meal_plan_selection_conflict
    case name_required
    case not_found
    case oauth_failed
    case oauth_unavailable
    case owner_cannot_leave
    case owner_required
    case personal_cookbook_invitation
    case personal_cookbook_required
    case rate_limited
    case recipe_save_conflict
    case recipe_save_gone
    case shared_cookbook_exists
    case text_required
    case text_too_long
    case unauthorized
    case update_failed
    case url_required
    case validation_failed
}

enum ImportErrorCode: String, CaseIterable {
    // Generated by bin/api-error-contract --generate. Do not edit.
    case import_failed
    case no_recipe_in_photo
}

enum ValidationFieldCode: String, CaseIterable {
    // Generated by bin/api-error-contract --generate. Do not edit.
    case base
    case cook_time
    case cover_image
    case email_address
    case import_image
    case name
    case password
    case password_challenge
    case password_confirmation
    case prep_time
    case servings
    case source_url
}

enum ValidationRuleCode: String, CaseIterable {
    // Generated by bin/api-error-contract --generate. Do not edit.
    case blank
    case confirmation
    case invalid
    case password_too_long
    case taken
    case too_long
    case too_short
}
